version: "3"
services:
  redis:
    image: redis:alpine
  db:
    image: postgres:9.6

  app:
    build: .
    volumes:
       - .:/usr/src/app
    command: rails server
    environment:
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis
    depends_on:
      - redis
      - db
    ports:
      - "3000"