version: "3"
services:
  db:
    image: postgres:10.2

  app:
    build: .
    volumes:
       - .:/usr/src/app
    command: rails server -b 0.0.0.0
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres@db
    depends_on:
      - db
    ports:
      - "3000:3000"